# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  docs:
    desc: Start the godoc documentation server on port 6060 and open in browser
    cmds:
      - bash scripts/docs.sh

  sse:
    desc: Start a sysinfo SSE producer on port 8082
    cmds:
      - go run . sse --listen_port 8082
